from __future__ import annotations

import csv
from datetime import datetime, timezone
import os
from threading import RLock
from typing import Any, Optional

from pydantic import BaseModel, EmailStr, Field, root_validator

from config import get_data_file


data_lock = RLock()

CLIENTES_FILE = get_data_file("CLIENTES_CSV", "clientes.csv")
PRODUCTOS_FILE = get_data_file("PRODUCTOS_CSV", "productos.csv")
INVENTARIO_FILE = get_data_file("INVENTARIO_CSV", "inventario.csv")
PEDIDOS_FILE = get_data_file("PEDIDOS_CSV", "pedidos.csv")

CLIENTES_HEADERS = ["id_cliente", "nombre", "correo", "direccion", "telefono", "activo"]
PRODUCTOS_HEADERS = ["id_producto", "descripcion", "precio", "activo"]
INVENTARIO_HEADERS = ["id_producto", "cantidad"]
PEDIDOS_HEADERS = ["id_pedido", "id_producto", "id_cliente", "cantidad", "costo", "estado", "created_at"]
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "postgres" if DATABASE_URL else "csv").strip().lower()


def _as_bool(value: Any, default: bool = True) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on", "si"}


def _as_float(value: Any, default: float = 0.0) -> float:
    if value in (None, ""):
        return default
    return float(value)


def _as_int(value: Any, default: int = 0) -> int:
    if value in (None, ""):
        return default
    return int(value)


def _model_dump(model: BaseModel) -> dict[str, Any]:
    if hasattr(model, "model_dump"):
        return model.model_dump()
    return model.dict()


def _read_rows(path) -> list[dict[str, str]]:
    if not path.exists():
        return []

    with open(path, "r", newline="", encoding="utf-8") as file_obj:
        reader = csv.DictReader(file_obj)
        return list(reader)


def _write_rows(path, headers: list[str], rows: list[dict[str, Any]]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as file_obj:
        writer = csv.DictWriter(file_obj, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)


def usando_postgres() -> bool:
    return STORAGE_BACKEND in {"postgres", "postgresql", "db", "database"} and bool(DATABASE_URL)


def _db_connect():
    import psycopg2
    from psycopg2.extras import RealDictCursor

    connect_kwargs = {"cursor_factory": RealDictCursor}
    if "sslmode=" not in DATABASE_URL.lower():
        connect_kwargs["sslmode"] = os.getenv("DATABASE_SSLMODE", "require")
    return psycopg2.connect(DATABASE_URL, **connect_kwargs)


def inicializar_postgres() -> None:
    if not usando_postgres():
        return

    with _db_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS clientes (
                    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre TEXT NOT NULL,
                    correo TEXT NOT NULL UNIQUE,
                    direccion TEXT NOT NULL,
                    telefono TEXT NOT NULL,
                    activo BOOLEAN NOT NULL DEFAULT TRUE
                );

                CREATE TABLE IF NOT EXISTS productos (
                    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    descripcion TEXT NOT NULL,
                    precio NUMERIC(12, 2) NOT NULL CHECK (precio > 0),
                    activo BOOLEAN NOT NULL DEFAULT TRUE
                );

                CREATE TABLE IF NOT EXISTS inventario (
                    id_producto INTEGER PRIMARY KEY REFERENCES productos(id_producto) ON DELETE CASCADE,
                    cantidad INTEGER NOT NULL CHECK (cantidad >= 0)
                );

                CREATE TABLE IF NOT EXISTS pedidos (
                    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
                    id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
                    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
                    costo NUMERIC(12, 2) NOT NULL CHECK (costo >= 0),
                    estado TEXT NOT NULL DEFAULT 'COMPLETADO',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                ALTER TABLE clientes ADD COLUMN IF NOT EXISTS direccion TEXT;
                ALTER TABLE clientes ADD COLUMN IF NOT EXISTS telefono TEXT;
                ALTER TABLE clientes ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;

                ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio NUMERIC(12, 2);
                ALTER TABLE productos ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;

                ALTER TABLE inventario ADD COLUMN IF NOT EXISTS cantidad INTEGER DEFAULT 0;

                ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS costo NUMERIC(12, 2) DEFAULT 0;
                ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'COMPLETADO';
                ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
                """
            )


def _sync_identity_sequence(cur, table_name: str, id_column: str) -> None:
    cur.execute("SELECT pg_get_serial_sequence(%s, %s) AS sequence_name;", (table_name, id_column))
    sequence_name = cur.fetchone()["sequence_name"]
    if not sequence_name:
        return

    cur.execute(
        f"""
        SELECT setval(
            %s,
            COALESCE((SELECT MAX({id_column}) FROM {table_name}), 1),
            COALESCE((SELECT MAX({id_column}) FROM {table_name}), 0) > 0
        );
        """,
        (sequence_name,),
    )


def cargar_clientes_postgres() -> list["Cliente"]:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    id_cliente,
                    nombre,
                    correo,
                    COALESCE(direccion, '') AS direccion,
                    COALESCE(telefono, '') AS telefono,
                    COALESCE(activo, TRUE) AS activo
                FROM clientes
                ORDER BY id_cliente;
                """
            )
            return [Cliente(**dict(row)) for row in cur.fetchall()]


def cargar_productos_postgres() -> list["Producto"]:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    id_producto,
                    descripcion,
                    COALESCE(precio, 0) AS precio,
                    COALESCE(activo, TRUE) AS activo
                FROM productos
                ORDER BY id_producto;
                """
            )
            return [
                Producto(
                    id_producto=row["id_producto"],
                    descripcion=row["descripcion"],
                    precio=float(row["precio"]),
                    activo=row["activo"],
                )
                for row in cur.fetchall()
            ]


def cargar_inventario_postgres() -> list["Inventario"]:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT id_producto, COALESCE(cantidad, 0) AS cantidad FROM inventario ORDER BY id_producto;")
            return [Inventario(**dict(row)) for row in cur.fetchall()]


def cargar_pedidos_postgres() -> list["Pedido"]:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    id_pedido,
                    id_producto,
                    id_cliente,
                    cantidad,
                    COALESCE(costo, 0) AS costo,
                    COALESCE(estado, 'COMPLETADO') AS estado,
                    COALESCE(created_at, NOW()) AS created_at
                FROM pedidos
                ORDER BY id_pedido;
                """
            )
            pedidos = []
            for row in cur.fetchall():
                pedidos.append(
                    Pedido(
                        id_pedido=row["id_pedido"],
                        id_producto=row["id_producto"],
                        id_cliente=row["id_cliente"],
                        cantidad=row["cantidad"],
                        costo=float(row["costo"]),
                        estado=row["estado"],
                        created_at=row["created_at"].isoformat(),
                    )
                )
            return pedidos


def guardar_clientes_postgres(clientes: list["Cliente"]) -> None:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            for cliente in clientes:
                row = _model_dump(cliente)
                cur.execute(
                    """
                    UPDATE clientes
                    SET nombre = %s,
                        correo = %s,
                        direccion = %s,
                        telefono = %s,
                        activo = %s
                    WHERE id_cliente = %s;
                    """,
                    (
                        row["nombre"],
                        str(row["correo"]).lower(),
                        row["direccion"],
                        str(row["telefono"]),
                        row["activo"],
                        row["id_cliente"],
                    ),
                )
                if cur.rowcount == 0:
                    cur.execute(
                        """
                        INSERT INTO clientes (id_cliente, nombre, correo, direccion, telefono, activo)
                        VALUES (%s, %s, %s, %s, %s, %s);
                        """,
                        (
                            row["id_cliente"],
                            row["nombre"],
                            str(row["correo"]).lower(),
                            row["direccion"],
                            str(row["telefono"]),
                            row["activo"],
                        ),
                    )
            _sync_identity_sequence(cur, "clientes", "id_cliente")


def guardar_productos_postgres(productos: list["Producto"]) -> None:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            for producto in productos:
                row = _model_dump(producto)
                cur.execute(
                    """
                    UPDATE productos
                    SET descripcion = %s,
                        precio = %s,
                        activo = %s
                    WHERE id_producto = %s;
                    """,
                    (row["descripcion"], row["precio"], row["activo"], row["id_producto"]),
                )
                if cur.rowcount == 0:
                    cur.execute(
                        """
                        INSERT INTO productos (id_producto, descripcion, precio, activo)
                        VALUES (%s, %s, %s, %s);
                        """,
                        (row["id_producto"], row["descripcion"], row["precio"], row["activo"]),
                    )
            _sync_identity_sequence(cur, "productos", "id_producto")


def guardar_inventarios_postgres(inventarios: list["Inventario"]) -> None:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            for item in inventarios:
                row = _model_dump(item)
                cur.execute(
                    """
                    UPDATE inventario
                    SET cantidad = %s
                    WHERE id_producto = %s;
                    """,
                    (row["cantidad"], row["id_producto"]),
                )
                if cur.rowcount == 0:
                    cur.execute(
                        """
                        INSERT INTO inventario (id_producto, cantidad)
                        VALUES (%s, %s);
                        """,
                        (row["id_producto"], row["cantidad"]),
                    )


def guardar_pedidos_postgres(pedidos: list["Pedido"]) -> None:
    inicializar_postgres()
    with _db_connect() as conn:
        with conn.cursor() as cur:
            for pedido in pedidos:
                row = _model_dump(pedido)
                cur.execute(
                    """
                    UPDATE pedidos
                    SET id_producto = %s,
                        id_cliente = %s,
                        cantidad = %s,
                        costo = %s,
                        estado = %s,
                        created_at = %s
                    WHERE id_pedido = %s;
                    """,
                    (
                        row["id_producto"],
                        row["id_cliente"],
                        row["cantidad"],
                        row["costo"],
                        row["estado"],
                        row["created_at"],
                        row["id_pedido"],
                    ),
                )
                if cur.rowcount == 0:
                    cur.execute(
                        """
                        INSERT INTO pedidos (id_pedido, id_producto, id_cliente, cantidad, costo, estado, created_at)
                        VALUES (%s, %s, %s, %s, %s, %s, %s);
                        """,
                        (
                            row["id_pedido"],
                            row["id_producto"],
                            row["id_cliente"],
                            row["cantidad"],
                            row["costo"],
                            row["estado"],
                            row["created_at"],
                        ),
                    )
            _sync_identity_sequence(cur, "pedidos", "id_pedido")


class Cliente(BaseModel):
    id_cliente: int
    nombre: str
    correo: EmailStr
    direccion: str
    telefono: str
    activo: bool = True


class ClienteRegistro(BaseModel):
    nombre: str
    correo: EmailStr
    direccion: str
    telefono: str
    activo: bool = True


class ClienteLogin(BaseModel):
    nombre: str
    telefono: str


class ClienteUpdate(BaseModel):
    nombre: Optional[str] = None
    correo: Optional[EmailStr] = None
    direccion: Optional[str] = None
    telefono: Optional[str] = None
    activo: Optional[bool] = None


class Producto(BaseModel):
    id_producto: int
    descripcion: str
    precio: float = Field(gt=0)
    activo: bool = True


class ProductoRegistro(BaseModel):
    descripcion: str
    precio: Optional[float] = None
    costo: Optional[float] = None
    costo_unitario: Optional[float] = None
    activo: bool = True

    @root_validator(pre=True)
    def _normalizar_precio(cls, values: dict[str, Any]) -> dict[str, Any]:
        precio = values.get("precio")
        if precio in (None, ""):
            precio = values.get("costo")
        if precio in (None, ""):
            precio = values.get("costo_unitario")
        values["precio"] = precio
        return values


class ProductoUpdate(BaseModel):
    descripcion: Optional[str] = None
    precio: Optional[float] = None
    costo: Optional[float] = None
    costo_unitario: Optional[float] = None
    activo: Optional[bool] = None

    @root_validator(pre=True)
    def _normalizar_precio(cls, values: dict[str, Any]) -> dict[str, Any]:
        precio = values.get("precio")
        if precio in (None, ""):
            precio = values.get("costo")
        if precio in (None, ""):
            precio = values.get("costo_unitario")
        if precio not in (None, ""):
            values["precio"] = precio
        return values


class Inventario(BaseModel):
    id_producto: int
    cantidad: int = Field(ge=0)


class InventarioRegistro(BaseModel):
    cantidad: int = Field(gt=0)


class InventarioAlta(BaseModel):
    id_producto: int
    cantidad_inicial: int = Field(ge=0)


class InventarioUpdate(BaseModel):
    cantidad: Optional[int] = Field(default=None, ge=0)


class Pedido(BaseModel):
    id_pedido: int
    id_producto: int
    id_cliente: int
    cantidad: int = Field(gt=0)
    costo: float = Field(ge=0)
    estado: str = "COMPLETADO"
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class PedidoRegistro(BaseModel):
    id_pedido: Optional[int] = None
    id_producto: int
    id_cliente: int
    cantidad: int = Field(gt=0)
    costo: Optional[float] = None
    estado: Optional[str] = None


class PedidoUpdate(BaseModel):
    cantidad: Optional[int] = Field(default=None, gt=0)
    estado: Optional[str] = None


def cargar_clientes() -> list[Cliente]:
    if usando_postgres():
        return cargar_clientes_postgres()

    clientes: list[Cliente] = []
    for row in _read_rows(CLIENTES_FILE):
        try:
            clientes.append(
                Cliente(
                    id_cliente=_as_int(row.get("id_cliente")),
                    nombre=(row.get("nombre") or "").strip(),
                    correo=(row.get("correo") or "").strip().lower(),
                    direccion=(row.get("direccion") or "").strip(),
                    telefono=(row.get("telefono") or "").strip(),
                    activo=_as_bool(row.get("activo"), default=True),
                )
            )
        except Exception:
            continue
    return clientes


def cargar_productos() -> list[Producto]:
    if usando_postgres():
        return cargar_productos_postgres()

    productos: list[Producto] = []
    for row in _read_rows(PRODUCTOS_FILE):
        try:
            precio = row.get("precio")
            if precio in (None, ""):
                precio = row.get("costo")
            if precio in (None, ""):
                precio = row.get("costo_unitario")

            productos.append(
                Producto(
                    id_producto=_as_int(row.get("id_producto")),
                    descripcion=(row.get("descripcion") or "").strip(),
                    precio=_as_float(precio),
                    activo=_as_bool(row.get("activo"), default=True),
                )
            )
        except Exception:
            continue
    return productos


def cargar_inventario() -> list[Inventario]:
    if usando_postgres():
        return cargar_inventario_postgres()

    inventario: list[Inventario] = []
    for row in _read_rows(INVENTARIO_FILE):
        try:
            inventario.append(
                Inventario(
                    id_producto=_as_int(row.get("id_producto")),
                    cantidad=_as_int(row.get("cantidad")),
                )
            )
        except Exception:
            continue
    return inventario


def cargar_pedidos() -> list[Pedido]:
    if usando_postgres():
        return cargar_pedidos_postgres()

    pedidos: list[Pedido] = []
    for row in _read_rows(PEDIDOS_FILE):
        try:
            pedidos.append(
                Pedido(
                    id_pedido=_as_int(row.get("id_pedido")),
                    id_producto=_as_int(row.get("id_producto")),
                    id_cliente=_as_int(row.get("id_cliente")),
                    cantidad=_as_int(row.get("cantidad")),
                    costo=_as_float(row.get("costo")),
                    estado=(row.get("estado") or "COMPLETADO").strip().upper(),
                    created_at=(row.get("created_at") or datetime.now(timezone.utc).isoformat()).strip(),
                )
            )
        except Exception:
            continue
    return pedidos


bd_clientes = cargar_clientes()
bd_productos = cargar_productos()
bd_inventario = cargar_inventario()
bd_pedidos = cargar_pedidos()


def guardar_clientes(clientes: list[Cliente]) -> None:
    if usando_postgres():
        guardar_clientes_postgres(clientes)
        return

    rows = []
    for cliente in clientes:
        row = _model_dump(cliente)
        row["correo"] = str(row["correo"]).lower()
        row["telefono"] = str(row["telefono"]).strip()
        rows.append(row)
    _write_rows(CLIENTES_FILE, CLIENTES_HEADERS, rows)


def guardar_productos(productos: list[Producto]) -> None:
    if usando_postgres():
        guardar_productos_postgres(productos)
        return

    rows = []
    for producto in productos:
        row = _model_dump(producto)
        row["precio"] = f"{float(row['precio']):.2f}"
        rows.append(row)
    _write_rows(PRODUCTOS_FILE, PRODUCTOS_HEADERS, rows)


def guardar_inventarios(inventarios: list[Inventario]) -> None:
    if usando_postgres():
        guardar_inventarios_postgres(inventarios)
        return

    rows = [_model_dump(item) for item in inventarios]
    _write_rows(INVENTARIO_FILE, INVENTARIO_HEADERS, rows)


def guardar_pedidos(pedidos: list[Pedido]) -> None:
    if usando_postgres():
        guardar_pedidos_postgres(pedidos)
        return

    rows = []
    for pedido in pedidos:
        row = _model_dump(pedido)
        row["costo"] = f"{float(row['costo']):.2f}"
        row["estado"] = str(row["estado"]).upper()
        rows.append(row)
    _write_rows(PEDIDOS_FILE, PEDIDOS_HEADERS, rows)


def sincronizar_archivos() -> None:
    with data_lock:
        guardar_clientes(bd_clientes)
        guardar_productos(bd_productos)
        guardar_inventarios(bd_inventario)
        guardar_pedidos(bd_pedidos)


def siguiente_id(items: list[Any], attr_name: str) -> int:
    if not items:
        return 1
    return max(int(getattr(item, attr_name)) for item in items) + 1
