services:
  shopnowui:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      ENABLE_RABBITMQ: "false"
    volumes:
      - ./clientes.csv:/app/clientes.csv
      - ./productos.csv:/app/productos.csv
      - ./inventario.csv:/app/inventario.csv
      - ./pedidos.csv:/app/pedidos.csv
